### ISSUE TITLE
Rename gh-pages to master

### ISSUE THREAD

**Issue by pathawks** [jekyll/directory#13]
How do you feel about changing the name of the `gh-pages` branch to `master`?

Since the website is the main (only) thing this repository is tracking, it makes sense to me that it would be the `master` branch. The `gh-pages` branch feels like it would be better suited for documentation regarding another project, rather than the primary branch of the project.

Thoughts?

**Comment by parkr** [comment]
Sounds good to me! Do you have the ability to do that?

**Comment by parkr** [comment]
Once your PR's are merged into `gh-pages`, create the `master` branch and change the Pages source in the Settings. 👌

**Comment by parkr** [comment]
Done!

**Comment by pathawks** [comment]
I don't believe I have write access to the repo. I wouldn't mind being a maintainer.

Might not be a bad idea to just give @jekyll/plugin-core access.

**Comment by parkr** [comment]
> Might not be a bad idea to just give @jekyll/plugin-core access.

I had the same thought. You have write access now! 😄
