### ISSUE TITLE
Add entry for all jekyll/* plugins

### ISSUE THREAD

**Issue by pathawks** [jekyll/directory#26]
We should create an entry for each of the official Jekyll team owned plugins

**Comment by DirtyF** [comment]
I can submit a PR for this if you want @pathawks

**Comment by pathawks** [comment]
@DirtyF Nothing would make me happier!

**Comment by DirtyF** [comment]
@pathawks Seriously? 😄

**Comment by pathawks** [comment]
```ruby
expect(things_that_would_make_me_happier).to be_nil
```

**Comment by DirtyF** [comment]
@pathawks what do you think of mentioning when a plugin is maintained by the core team? (à la Middleman https://directory.middlemanapp.com/#/extensions/official)

**Comment by ghost** [comment]
@DirtyF does it make a difference? like, does the user want to know that?

**Comment by DirtyF** [comment]
@pnn  Good question.  🤔 

This label would be reserved to actively maintained plugins, tested with latest Jekyll version. Maybe other plugins outside of the core team, could inherit the label.

It serves as some kind of warranty that users can be confident regarding the stability of the plugin. We can't speak for everyone, but we can at least reassure users that these few will work fine.

Or we could just list plugins that were tested and drop the label.

**Comment by ghost** [comment]
@DirtyF yeah, i think it might be better not to reserve the 'actively maintained' label for the core team and instead apply it to all plugins that are maintained/tested/whatever. let's go the extra mile for this

**Comment by pathawks** [comment]
Yeah, I think it would be better to display the last updated date or maybe the latest version of Jekyll a plugin has been tested against, rather than “Hey, I made this”

**Comment by DirtyF** [comment]
@pathawks good idea.

**Comment by parkr** [comment]
I have heard people express a desire to only use official plugins because they're worried about long-term support. So there might be use signaling that.

Beyond an "official" plugin, it might be helpful to see "enabled on GitHub Pages" which could signal what users can use on GitHub Pages.

**Comment by pathawks** [comment]
Yes, a filter for GHP enabled would be helpful for sure.
